void load_board(const char* filename, char board[9][9]);
void display_board(const char board[9][9]);
bool is_complete(const char board[9][9]);
bool is_complete(const char board[9][9], int &empty_row, int &empty_column);
bool make_move(const char* position, char digit, char board[9][9]);
bool is_position_valid(int row, int column, char digit, const char board[9][9]);
bool save_board(const char *filename, const char board[9][9]);
bool solve_board(char board[9][9]);
bool count_mistakes(char board[9][9], int &mistakes);
void measure_execution_time(char board[9][9], const char* board_name);
